### PR TITLE
Use ip@5: if available instead of sp

### PR DESCRIPTION
**Pull request by climbfuji**
The sp library is deprecated and replaced by ip@5 and newer (drop-in replacement). While sp@2.5.0 is still in spack-stack-1.8.0, ip-5.0.0 is also available. We expect sp to be removed in spack-stack-1.9.0.

This PR goes with https://github.com/NCAR/ccpp-physics/pull/1090

### CODE REVIEW

**Review by dustinswales — APPROVED** [review]
All tests pass.
Looks good to me.

**Comment by climbfuji** [comment]
ping

**Comment by grantfirl** [comment]
@scrasmussen I saw https://github.com/NCAR/ccpp-scm/discussions/551. I'm going to run some tests on Hera to verify that this works with spack-stack 1.8.0 before I approve. If it works, we can merge it, although I don't think that we want the SCM to get ahead of where the UFS is in terms of which version spack-stack is being used by default: https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_hera.intel.lua

**Comment by scrasmussen** [comment]
@grantfirl If we don't want the SCM to get ahead I can just answer gabersek with instructions to checkout my updated [fature/ip5](https://github.com/scrasmussen/ccpp-scm/tree/feature/ip5) branch and use that as a workaround until the default spack-stack gets updated and we merge this? (Hopefully I'm understanding the situation correctly)

**Comment by grantfirl** [comment]
> @grantfirl If we don't want the SCM to get ahead I can just answer gabersek with instructions to checkout my updated [fature/ip5](https://github.com/scrasmussen/ccpp-scm/tree/feature/ip5) branch and use that as a workaround until the default spack-stack gets updated and we merge this? (Hopefully I'm understanding the situation correctly)

I think that it should be OK to merge before UFS updates their spack-stack version because Dom changed the CMakeLists to look for IP first and then SP if not found. This should work fine with spack-stack 1.6 until it is updated to coincide with UFS. gabersek was already doing something "nonstandard" by trying the SCM with spack-stack 1.8, but it wouldn't work because CMakeLists.txt didn't even know to look for IP yet. It's weird, though, because sp supposedly still exists in 1.8, so I'm not 100% sure why the issue cropped up yet.

**Comment by grantfirl** [comment]
Note that the RTs run via CI do not use IP. They are falling back to SP. The model is running, but apparently all baselines are changed? That seems odd to me.

On another note, I have an older version of spack-stack installed on my Mac that has ip that tries to get used. When it does, I'm getting compilation errors in RRTMGP.

ccpp-scm-new/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/extensions/cloud_optics/mo_cloud_optics.F90:530:23:

  530 |         !$omp map(from:optical_props%tau)
      |                       1
Error: List item '__tmp_type_ty_optical_props_1scl' with allocatable components is not permitted in map clause at (1)
ccpp-scm-new/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/extensions/cloud_optics/mo_cloud_optics.F90:545:23:

  545 |         !$omp map(from:optical_props%tau, optical_props%ssa, optical_props%g)
      |                       1
Error: List item '__tmp_type_ty_optical_props_2str' with allocatable components is not permitted in map clause at (1)
/ccpp-scm-new/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/extensions/cloud_optics/mo_cloud_optics.F90:545:41:

  545 |         !$omp map(from:optical_props%tau, optical_props%ssa, optical_props%g)
      |                                         1
Error: List item '__tmp_type_ty_optical_props_2str' with allocatable components is not permitted in map clause at (1)
/ccpp-scm-new/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/extensions/cloud_optics/mo_cloud_optics.F90:545:60:

I'm going to try to use spack-stack 1.8.0 on Hera and test with IP to see if I get the same compilation error.

**Comment by grantfirl** [comment]
@dustinswales When you get a chance, try to compile this PR on Hera with spack-stack 1.8.0 and see if the compilation error seems easily fixable to you. This doesn't make a whole lot of sense to me because I doubt RRTMGP has anything to do with the IP library, but it fails nevertheless. On my mac version of spack-stack, I'm getting failures in mo_cloud_optics.F90 related to openmp. On Hera, I'm getting compilation errors in mo_fluxes_broadband_kernels.F90 also related to openmp statements.

**Comment by grantfirl** [comment]
I can compile everything successfully on Hera with the same exact spack-stack 1.8.0 stack substituting sp/2.5.0 back in for ip/5.0.0.

**Review by grantfirl — CHANGES_REQUESTED** [review]
I'd like to understand why ip/5.0.0 is causing RRTMGP to fail compilation before approving this. Granted, the code as-is will find sp/2.5.0 using the default spack-stack 1.6.0, but when updating to 1.8.0 and ip/5.0.0, this problem will need to be figured out anyway.

**Comment by dustinswales** [comment]
@grantfirl Sorry for not getting around to this earlier.
Beyond changing MODULEPATH and the sp-ip, I also had to change the cmake and python to get the environment right.
-prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/modulefiles/Core")
+prepend_path("MODULEPATH", "/contrib/spack-stack/spack-stack-1.8.0/envs/mapl-2.40.3-intel-2021.5.0/install/modulefiles/Core") 
-load("stack-python/3.10.13")
+load("stack-python/3.11.7")
-load("cmake/3.23.1")
+load("cmake/3.27.9") 
-load("sp/2.5.0")
+load("ip/5.0.0")

When I do this, I get errors in the RRTMGP code about the OMP commands, not the same errors as you:
/scratch1/BMC/gmtb/Dustin.Swales/UFS/NCAR-ccpp-1090/ccpp-scm/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/rte/kernels/mo_fluxes_broadband_kernels.F90(44): error #5512: This language feature is not supported on this platform
!$omp target enter data map(to:spectral_flux) map(alloc:broadband_flux)
------^
/scratch1/BMC/gmtb/Dustin.Swales/UFS/NCAR-ccpp-1090/ccpp-scm/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/rte/kernels/mo_fluxes_broadband_kernels.F90(60): error #5512: This language feature is not supported on this platform
!$omp target exit data map(release:spectral_flux) map(from:broadband_flux)
------^
/scratch1/BMC/gmtb/Dustin.Swales/UFS/NCAR-ccpp-1090/ccpp-scm/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/rte/kernels/mo_fluxes_broadband_kernels.F90(79): error #5512: This language feature is not supported on this platform
!$omp target enter data map(to:spectral_flux_dn, spectral_flux_up) map(alloc:broadband_flux_net)
------^
/scratch1/BMC/gmtb/Dustin.Swales/UFS/NCAR-ccpp-1090/ccpp-scm/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/rte/kernels/mo_fluxes_broadband_kernels.F90(101): error #5512: This language feature is not supported on this platform
!$omp target exit data map(release:spectral_flux_dn, spectral_flux_up) map(from:broadband_flux_net)
------^
/scratch1/BMC/gmtb/Dustin.Swales/UFS/NCAR-ccpp-1090/ccpp-scm/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/rte/kernels/mo_fluxes_broadband_kernels.F90(118): error #5512: This language feature is not supported on this platform
!$omp target enter data map(to:flux_dn, flux_up) map(alloc:broadband_flux_net)
------^
/scratch1/BMC/gmtb/Dustin.Swales/UFS/NCAR-ccpp-1090/ccpp-scm/ccpp/physics/physics/Radiation/RRTMGP/rte-rrtmgp/rte/kernels/mo_fluxes_broadband_kernels.F90(127): error #5512: This language feature is not supported on this platform
!$omp target exit data map(release:flux_dn, flux_up) map(from:broadband_flux_net)

If I add a flag to turn off openmp for these schemes
 if(SCHEMES_OPENMP_OFF)
   SET_PROPERTY(SOURCE ${SCHEMES_OPENMP_OFF}
-               APPEND_STRING PROPERTY COMPILE_FLAGS " ${CMAKE_Fortran_FLAGS_PHYSICS}")
+               APPEND_STRING PROPERTY COMPILE_FLAGS " ${CMAKE_Fortran_FLAGS_PHYSICS} -qno-openmp ")
   list(REMOVE_ITEM SCHEMES ${SCHEMES_OPENMP_OFF})

It builds w/o errors.

**Comment by grantfirl** [comment]
This can be closed since this was taken care of in #662
